dataset: cora  # Choices: ["cora", "citeseer", "pubmed", "microseer"]
mode: validation  # Choices: ["validation", "test"]
seed: 0
features: 0  # Choices: [0,1]
paper_leak: 0.0  # Choices: [1., 10., 100., 100000.]
paper_threshold: 4.519  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
train_ref: 1  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
feature_ref: 1  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
validation_ref: 1000  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
test_ref: 1000  # Same as validation_ref
topic_leak: 0.0  # Choices: [1., 10., 100., 100000.]
topic_threshold: 0.00001  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
feature_leak: 0.0  # Choices: [1., 10., 100., 100000.]
feature_threshold: 0.25  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
graph_weight: 63.75  # Choices: [0.5, 1.0, 10.0, 100.0]
graph_delay: 1  # Choices: [1., 2., 5., 10., 20.]
train_to_topic_weight: 4.33  # Choices: [0.5, 1.0, 10.0, 100.0]
train_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
validation_to_topic_weight: 0.00001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
validation_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
test_to_topic_weight: 0.00001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
test_to_topic_delay: 1  # Choices: [1., 2., 5., 10., 20.]
paper_to_feature_weight: 2.8 # Choices: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
feature_to_paper_weight: 2.8 # Choices: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
paper_to_feature_delay: 1  # Choices: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
feature_to_topic:        0          # enable this block
feature_to_topic_weight: 0        # base weight
feature_to_topic_delay:  0           # or whatever delay makes sense
feature_to_topic_stdp:   0           # turn STDP on if you want it plastic
simtime: 6  # Choices: [5., 10., 20., 30., 40., 50., 75., 100., 150., 200.]
processes: 8  # Adjust based on machine capabilities
monitors: False
paper_to_feature_stdp: False
paper_to_feature_weighted: False
apos: [70.3, 4.901, 0.469, 0.464, 0.095]
aneg: [.0005]
stdp_timesteps: 5
dump_json: 1

bo:
  max_iterations: 1000
  num_initial_points: 100
  output_dir: "bo-results-cora"
  save_iteration: 5