dataset: cora  # Choices: ["cora", "citeseer", "pubmed"]
input_spike_value: 100.0
mode: validation  # Choices: ["validation", "test"]
monitors: False
paper_to_feature_stdp: False
paper_to_feature_weighted: False
processes: 24  # Adjust based on machine capabilities
seed: 0
simtime: 5.0  # Choices: [5., 10., 20., 30., 40., 50., 75., 100., 150., 200.]

bo:
  num_initial_points: 500
  max_iterations: 10000
graph:
  weight: 10.0  # Choices: [0.5, 1.0, 10.0, 100.0]
  delay: 1.0  # Choices: [1., 2., 5., 10., 20.]
paper:
  leak: 0.0  # Choices: [1., 10., 100., 100000.]
  threshold: 1.0  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
stdp:
  A_pos: 0.1  # Choices: [0.01, 0.1, 1.0, 10.0]
  A_neg: 0.0001  # Choices: [0.00001, 0.0001, 0.001, 0.01]
test:
  ref: 1000.0  # Same as validation_ref
test_to_topic:
  weight: 0.001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
  delay: 1.0  # Choices: [1., 2., 5., 10., 20.]
topic:
  leak: 0.0  # Choices: [1., 10., 100., 100000.]
  threshold: 0.5  # Choices: [0.25, 0.5, 0.75, 1.0, 1.5]
train:
  ref: 1.0  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
train_to_topic:
  weight: 1.0  # Choices: [0.5, 1.0, 10.0, 100.0]
  delay: 1.0  # Choices: [1., 2., 5., 10., 20.]
validation:
  ref: 1000.0  # Choices: [1.0, 5.0, 10.0, 100.0, 1000.0]
validation_to_topic:
  weight: 0.001  # Choices: [0.001, 0.005, 0.01, 0.05, 0.1]
  delay: 1.0  # Choices: [1., 2., 5., 10., 20.]
wandb:
  enabled: True
  project: sgnn-superneuro-cora-bo-no-features-test